@startuml
[*] --> 상품_페이지 : 페이지 진입
state 상품_페이지 {
  [*] --> 초기상태 : 매장 목록을 가져온다.
  초기상태 --> 상품_선택단계 : 유저가 매장을 선택한 뒤

  상품_선택단계 -up[dashed]-> 초기상태 : 유저는 행동을 취소 할 수 있다.
  상품_선택단계 --> 옵션_선택단계 : 유저가 상품을 선택 한 뒤

  옵션_선택단계 -up[dashed]-> 상품_선택단계 : 유저는 행동을 취소 할 수 있다.
  옵션_선택단계 -up-> 장바구니 : 옵션을 선택하면 제품은 장바구니에 담긴다.
  장바구니 -right[dashed]-> 초기상태 : 다른 매장을 선택하거나, 상품을 삭제하면 장바구니는 초기화된다.
}

초기상태 : * 매장목록 = List<매장>

상품_선택단계 : * 매장목록 = List<매장>
상품_선택단계 : * 선택한 매장 = 매장 식별정보
상품_선택단계 : * 상품목록 = List<상품>

옵션_선택단계 : * 매장목록 = List<매장>
옵션_선택단계 : * 선택한 매장 = 매장 식별정보
옵션_선택단계 : * 상품목록 = List<상품>
옵션_선택단계 : * 선택한 상품 = 상품 식별정보
옵션_선택단계 : * 상품의 옵션목록 = List<상품옵션>
옵션_선택단계 : * 선택한 옵션목록 = List<옵션 식별정보>

장바구니 : * 매장목록 = List<매장>
장바구니 : * 선택한 매장 = 매장 식별정보
장바구니 : * 상품목록 = List<상품>
장바구니 : * 선택한 상품 = 상품식별정보
장바구니 : * 상품의 옵션목록 = List<상품옵션>
장바구니 : * 선택된 옵션 = List<옵션 식별정보>
@enduml